import React, { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { useTheme } from "../../context/ThemeContext";
import {
  Zap,
  Search,
  BookOpen,
  CheckCircle2,
  Award,
  Mic,
  TrendingUp,
  ArrowRight,
  Sparkles,
  ChevronRight,
  ShieldCheck,
  Layers,
} from "lucide-react";

export default function MagicPipeline() {
  const { isDark } = useTheme();
  const [activeStep, setActiveStep] = useState(0);
  const [autoPlay, setAutoPlay] = useState(true);

  const pipelineSteps = [
    {
      id: 0,
      badge: "Step 1: Gap Detected",
      title: "Target Job Matcher & Gap Analyzer",
      description:
        "Paste any target job description. LifeOS instantly matches your resume against required qualifications and identifies missing skills.",
      outputLabel: "Detected Missing Skill:",
      outputVal: "Redis Distributed Caching & Rate Limiting",
      icon: Search,
      color: "from-sky-500 to-blue-600",
      accent: "text-sky-400",
      borderGlow: "border-sky-500/40",
      actionText: "1-Click Generate Remediation Plan ➔",
    },
    {
      id: 1,
      badge: "Step 2: Instant Curriculum",
      title: "Study Planner & Micro-Quizzes",
      description:
        "LifeOS auto-generates a tight 3-day outcome-driven study curriculum with daily active recall checkpoints.",
      outputLabel: "Generated Plan:",
      outputVal: "3-Day Master Redis: PubSub, Streams & Eviction",
      icon: BookOpen,
      color: "from-brand-indigo to-purple-600",
      accent: "text-brand-indigo",
      borderGlow: "border-brand-indigo/40",
      actionText: "Launch Timed Diagnostic Quiz ➔",
    },
    {
      id: 2,
      badge: "Step 3: Verification",
      title: "AI Quiz & Skill Certification",
      description:
        "Take a timed diagnostic quiz generated by Gemini 2.5 Flash. Scoring 80%+ certifies your competency.",
      outputLabel: "Diagnostic Score:",
      outputVal: "92% Score (Passed Master Level)",
      icon: CheckCircle2,
      color: "from-emerald-500 to-teal-600",
      accent: "text-emerald-400",
      borderGlow: "border-emerald-500/40",
      actionText: "Award Verified Credential Badge ➔",
    },
    {
      id: 3,
      badge: "Step 4: Permanent Ledger",
      title: "Verified Skill Ledger",
      description:
        "A verifiable certified badge is written to your permanent profile and automatically tailored into your resume bullet points.",
      outputLabel: "Ledger Update:",
      outputVal: "Verified Badge #9241: Redis Architect",
      icon: Award,
      color: "from-purple-600 to-indigo-600",
      accent: "text-purple-400",
      borderGlow: "border-purple-500/40",
      actionText: "Practice in AI Mock Interview ➔",
    },
    {
      id: 4,
      badge: "Step 5: Voice Mock Studio",
      title: "AI Mock Interview Studio",
      description:
        "Our turn-by-turn conversational AI tests your new knowledge with realistic technical & architectural interview questions.",
      outputLabel: "Interview Verdict:",
      outputVal: "STRONG HIRE (Readiness: 94%)",
      icon: Mic,
      color: "from-brand-sky to-cyan-500",
      accent: "text-brand-sky",
      borderGlow: "border-brand-sky/40",
      actionText: "Boost Universal Life Score ➔",
    },
    {
      id: 5,
      badge: "Step 6: Metric Surge",
      title: "Universal Life Score Engine",
      description:
        "The completed milestones trigger immutable positive snapshots across your Career and Learning dimensions.",
      outputLabel: "Life Score Surge:",
      outputVal: "+5.8 Points (88.4 ➔ 94.2 Total Score)",
      icon: TrendingUp,
      color: "from-emerald-400 via-teal-500 to-indigo-600",
      accent: "text-emerald-400",
      borderGlow: "border-emerald-500/40",
      actionText: "Experience Full Ecosystem Free ➔",
    },
  ];

  // Auto-cycle through pipeline nodes
  useEffect(() => {
    if (!autoPlay) return;
    const timer = setInterval(() => {
      setActiveStep((prev) => (prev + 1) % pipelineSteps.length);
    }, 4000);
    return () => clearInterval(timer);
  }, [autoPlay, pipelineSteps.length]);

  const current = pipelineSteps[activeStep];

  return (
    <section id="pipeline" className="relative py-20 md:py-28 overflow-hidden">
      {/* Background Neon Energy Grid */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden">
        <div
          className={`absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[500px] rounded-full blur-[150px] opacity-25 ${
            isDark ? "bg-brand-indigo/30" : "bg-sky-200/50"
          }`}
        />
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto mb-14">
          <div
            className={`inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full text-xs font-bold border mb-4 backdrop-blur-md ${
              isDark
                ? "bg-brand-sky/10 border-brand-sky/30 text-brand-sky"
                : "bg-sky-50 border-sky-200 text-brand-sky"
            }`}
          >
            <Zap className="w-3.5 h-3.5 text-brand-sky" />
            <span>THE 1-CLICK MAGIC PIPELINE</span>
          </div>

          <h2
            className={`text-3xl sm:text-4xl lg:text-5xl font-black tracking-tight leading-tight ${
              isDark ? "text-white" : "text-slate-900"
            }`}
          >
            How Modules Talk to Each Other.
            <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-sky via-brand-indigo to-emerald-400">
              Zero Manual Effort. Complete Flow.
            </span>
          </h2>

          <p
            className={`mt-4 text-sm sm:text-base md:text-lg font-normal leading-relaxed ${
              isDark ? "text-slate-400" : "text-slate-600"
            }`}
          >
            Watch how a single discovered skill gap flows automatically across Study Plans, AI Quizzes, Skill Badges, and Mock Interviews into your Life Score.
          </p>
        </div>

        {/* Step Navigation Pill Stepper */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2 sm:gap-3 mb-8">
          {pipelineSteps.map((step, idx) => {
            const Icon = step.icon;
            const isActive = activeStep === idx;
            return (
              <button
                key={step.id}
                onClick={() => {
                  setActiveStep(idx);
                  setAutoPlay(false);
                }}
                className={`p-3 rounded-2xl border text-left transition-all duration-300 cursor-pointer relative overflow-hidden group ${
                  isActive
                    ? isDark
                      ? "bg-[#0e131f] border-brand-sky shadow-[0_0_25px_rgba(14,165,233,0.3)] scale-[1.03]"
                      : "bg-white border-brand-indigo shadow-[0_10px_25px_rgba(99,102,241,0.15)] scale-[1.03]"
                    : isDark
                    ? "bg-[#0e131f]/50 border-slate-800 hover:border-slate-700 text-slate-400"
                    : "bg-white/60 border-slate-200 hover:border-slate-300 text-slate-600"
                }`}
              >
                {/* Active Indicator Bar */}
                {isActive && (
                  <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-brand-sky via-brand-indigo to-brand-emerald" />
                )}

                <div className="flex items-center gap-2 mb-1.5">
                  <div
                    className={`w-7 h-7 rounded-xl flex items-center justify-center text-xs font-bold ${
                      isActive
                        ? "bg-gradient-to-tr from-brand-indigo to-brand-sky text-white"
                        : "bg-slate-700/20 text-slate-400"
                    }`}
                  >
                    <Icon className="w-3.5 h-3.5" />
                  </div>
                  <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                    Node 0{idx + 1}
                  </span>
                </div>

                <div
                  className={`text-xs font-bold truncate ${
                    isActive
                      ? isDark
                        ? "text-white"
                        : "text-slate-900"
                      : "text-slate-400"
                  }`}
                >
                  {step.title.split(" & ")[0]}
                </div>
              </button>
            );
          })}
        </div>

        {/* Active Node Showcase Display Card */}
        <div
          className={`rounded-3xl p-6 sm:p-10 border backdrop-blur-2xl transition-all duration-500 shadow-2xl relative overflow-hidden ${
            isDark
              ? "bg-[#0e131f]/90 border-slate-800 shadow-[0_20px_60px_rgba(0,0,0,0.6)]"
              : "bg-white/90 border-slate-200 shadow-[0_20px_50px_rgba(99,102,241,0.08)]"
          }`}
        >
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
            {/* Left: Step Details */}
            <div className="lg:col-span-7">
              <div className="flex items-center gap-2 mb-3">
                <span className="px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider bg-brand-sky/15 text-brand-sky border border-brand-sky/30">
                  {current.badge}
                </span>
                <span className="text-xs text-slate-400 font-semibold">
                  Autonomous 1-Click Bridge
                </span>
              </div>

              <h3
                className={`text-2xl sm:text-3xl font-extrabold mb-4 ${
                  isDark ? "text-white" : "text-slate-900"
                }`}
              >
                {current.title}
              </h3>

              <p
                className={`text-sm sm:text-base leading-relaxed mb-6 ${
                  isDark ? "text-slate-300" : "text-slate-600"
                }`}
              >
                {current.description}
              </p>

              {/* Action Bridge Button */}
              <div className="flex flex-wrap items-center gap-4">
                <button
                  onClick={() => setActiveStep((prev) => (prev + 1) % pipelineSteps.length)}
                  className="inline-flex items-center gap-2 px-6 py-3 rounded-xl text-xs font-bold text-white bg-gradient-to-r from-brand-indigo via-brand-sky to-brand-sky-light hover:opacity-95 shadow-md shadow-brand-indigo/30 transition-all cursor-pointer"
                >
                  <span>{current.actionText}</span>
                  <ChevronRight className="w-4 h-4" />
                </button>

                <button
                  onClick={() => setAutoPlay(!autoPlay)}
                  className="text-xs font-semibold text-slate-400 hover:text-slate-300 underline"
                >
                  {autoPlay ? "⏸ Pause Auto Cycle" : "▶ Resume Auto Cycle"}
                </button>
              </div>
            </div>

            {/* Right: Live Interactive Output Inspector */}
            <div className="lg:col-span-5">
              <div
                className={`p-6 rounded-2xl border transition-all ${
                  isDark ? "bg-[#07090e]/80 border-slate-800" : "bg-slate-50 border-slate-200"
                }`}
              >
                <div className="flex items-center justify-between text-xs font-bold text-slate-400 mb-3">
                  <span className="flex items-center gap-1.5">
                    <Sparkles className="w-3.5 h-3.5 text-brand-sky" />
                    Live Ecosystem Data Stream
                  </span>
                  <span className="text-[10px] uppercase font-extrabold px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400">
                    Live Verified
                  </span>
                </div>

                <div className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">
                  {current.outputLabel}
                </div>

                <div
                  className={`text-base sm:text-lg font-black tracking-tight p-3.5 rounded-xl border mb-4 ${
                    isDark
                      ? "bg-[#0e131f] border-brand-indigo/30 text-brand-sky"
                      : "bg-white border-slate-200 text-brand-link shadow-sm"
                  }`}
                >
                  {current.outputVal}
                </div>

                <div className="space-y-2 text-xs font-medium text-slate-400">
                  <div className="flex items-center justify-between">
                    <span>Cross-Module Payload:</span>
                    <span className="font-mono text-emerald-400">JSON 0-Loss Synced</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span>Life Score Engine Sync:</span>
                    <span className="font-mono text-brand-sky">Realtime Logged</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
